// ============================================================
// src/data.js  –  ข้อมูลกลางและ constants ของระบบราคากลาง
// ============================================================

const CATEGORIES = [
  { id: 'all',               label: 'ทั้งหมด',        short: 'ALL'    },
  { id: 'Notebook',          label: 'Notebook',        short: 'NB'     },
  { id: 'AIO',               label: 'All-in-One',      short: 'AIO'    },
  { id: 'AI-COM',            label: 'AI Computer',     short: 'AI'     },
  { id: 'PC',                label: 'Desktop PC',      short: 'PC'     },
  { id: 'gaming-desktop-pc', label: 'Gaming Desktop',  short: 'GAME'   },
  { id: 'mini-pc',           label: 'Mini PC',         short: 'MINI'   },
  { id: 'Server',            label: 'Server',          short: 'SVR'    },
];

const CAT_COLORS = {
  'Notebook':          '#2563EB',
  'AIO':               '#7C3AED',
  'AI-COM':            '#DB2777',
  'PC':                '#059669',
  'gaming-desktop-pc': '#DC2626',
  'mini-pc':           '#EA580C',
  'Server':            '#0369A1',
};

const SPEC_GROUPS = [
  {
    id: 'spec', label: 'ข้อมูลจำเพาะ',
    fields: [
      'Processor','Chipset','CPU Series','AI Engine','AI Performance',
      'Graphics','Display Screen','Main Memory','Memory Slot','Max Memory',
      'Storage','Storage Slot','Expansion Slots','Optical Disk Drive',
      'Web Camera','Sound Technology','Audio Jack','Audio','Speaker',
      'OS','Special Feature','What\'s in the box?'
    ],
  },
  {
    id: 'conn', label: 'การเชื่อมต่อ',
    fields: [
      'Wireless','Bluetooth','Ports','Port',
      'Front I/O Port','Rear I/O Port','Front I/O ports','Back I/O ports',
      'Network','CardReader'
    ],
  },
  {
    id: 'power', label: 'กำลังไฟ',
    fields: ['Power Adapter','Power Supply','Battery'],
  },
  {
    id: 'general', label: 'ข้อมูลทั่วไป',
    fields: [
      'Dimension (cm)','Net Weight (kg)','Package Dimension (cm)',
      'Gross Weight (kg)','Volume (cm³)','Material',
      'Keyboard Type','Keyboard','Mouse','Backlit','Touchpad','Finger Print',
      'Form Factor','RAID','System Management'
    ],
  },
  {
    id: 'warranty', label: 'การรับประกัน',
    fields: ['warranty'],
  },
];

const USERS = [
  { id: 1, username: 'admin',  password: 'admin123', name: 'ผู้ดูแลระบบ',          role: 'admin', department: 'ฝ่ายไอที'    },
  { id: 2, username: 'user01', password: 'user123',  name: 'นายสมชาย ใจดี',       role: 'user',  department: 'ฝ่ายพัสดุ'  },
  { id: 3, username: 'user02', password: 'user123',  name: 'นางสาวสมหญิง มีสุข',  role: 'user',  department: 'ฝ่ายจัดซื้อ' },
];

const INITIAL_PRODUCTS = [
  // ─── Notebook ────────────────────────────────────────────────
  {
    id: 'nb-001', category: 'Notebook', brand: 'ASUS',
    model: 'Vivobook 16 (X1607CA-MB535WA)',
    price: 25900, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':         'Intel Core Ultra 5 225H (1.7GHz, up to 4.9GHz, 14C/14T, 18MB Intel Smart Cache)',
      'Chipset':           'Intel SoC Platform',
      'CPU Series':        'Core Ultra 5',
      'AI Engine':         'Intel AI Boost',
      'Graphics':          'Intel Arc Graphics (Integrated Graphics)',
      'Display Screen':    '16.0" 1920x1200 (WUXGA) 16:10, IPS, 60Hz, 300nits, Anti-glare, 45% NTSC',
      'Main Memory':       '16GB DDR5 Onboard memory',
      'Memory Slot':       '1x DDR5 SO-DIMM slot',
      'Max Memory':        'Up to 32GB',
      'Storage':           '512GB M.2 NVMe PCIe 4.0 SSD',
      'Storage Slot':      '1x M.2 2280 PCIe 4.0x4 (Occupied)',
      'Optical Disk Drive':'None',
      'Web Camera':        'FHD camera with IR function to support Windows Hello; With privacy shutter',
      'Sound Technology':  'SonicMaster',
      'Audio Jack':        '1x 3.5mm Combo Audio Jack',
      'Speaker':           '• Built-in speaker\n• Built-in array microphone',
      'OS':                'Windows 11 Home + Microsoft Office Home 2024 + Microsoft 365 Basic',
      'Wireless':          'Wireless 802.11ax (Wi-Fi 6)',
      'Bluetooth':         'Bluetooth 5.2',
      'Ports':             '2x USB 3.2 Gen 1 Type-A\n2x USB 3.2 Gen 1 Type-C with display / power delivery\n1x HDMI 1.4',
      'Network':           'N/A',
      'CardReader':        'N/A',
      'Power Adapter':     'TYPE-C, 65W AC Adapter, Output: 20V DC, 3.25A',
      'Battery':           '42WHrs, 3S1P, 3-cell Li-ion',
      'Dimension (cm)':    '(W x L x H) : 35.70 x 25.06 x 1.99 cm',
      'Net Weight (kg)':   '1.88 kg',
      'Package Dimension (cm)': '(W x L x H) : 13.00 x 49.00 x 31.00 cm',
      'Gross Weight (kg)': '4.00 kg',
      'Volume (cm³)':      '19,747.00 cm³',
      'Keyboard Type':     'ENG/TH Backlit Chiclet Keyboard with Num-key',
      'Backlit':           'Yes',
      'Touchpad':          'Precision touchpad',
      'warranty':          '• LCD cover-material: Plastic\n• Top case-material: Plastic\n• Bottom case-material: Plastic',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },

  // ─── AIO ─────────────────────────────────────────────────────
  {
    id: 'aio-001', category: 'AIO', brand: 'HP',
    model: 'HP 24-ct2006d (C8BZ9PA#AKL)',
    price: 28500, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':      'AMD Ryzen AI 5 330 Processor (2.0GHz up to 4.5GHz, 4C/8T)',
      'Chipset':        'AMD SoC Platform',
      'CPU Series':     'Ryzen AI 5',
      'AI Engine':      'AMD Ryzen AI (NPU 50 TOPS)',
      'Graphics':       'AMD Radeon 820M Graphics (Integrated Graphics)',
      'Display Screen': '23.8" 1920x1080 (FHD), IPS, three-sided micro-edge, anti-glare, 250 nits, 99% sRGB',
      'Main Memory':    '16GB (2x 8GB) DDR5-5600 SO-DIMM',
      'Memory Slot':    '2x DDR5 SO-DIMM slots',
      'Storage':        '512GB PCIe NVMe Value M.2 2280 SSD',
      'Storage Slot':   '1x M.2 SSD (Occupied)',
      'Web Camera':     'HP True Vision 1080p FHD IR tilt privacy camera with dual array digital microphones',
      'Audio':          'HD Audio',
      'Speaker':        'Dual 2W speakers',
      'OS':             'Windows 11 Home + Microsoft Office Home 2024',
      'Wireless':       'Wireless 802.11ax (Wi-Fi 6)',
      'Bluetooth':      'Bluetooth 5.4',
      'Ports':          '1x USB Type-C 5Gbps\n2x USB Type-A 5Gbps\n2x USB 2.0 Type-A\n1x HDMI-out 1.4\n1x headphone/microphone combo',
      'Network':        '10/100/1000 LAN',
      'Power Adapter':  '90W Smart AC power adapter',
      'Dimension (cm)': '(W x L x H) : 54.05 x 18.63 x 48.49 cm',
      'Net Weight (kg)':'5.53 kg',
      'Package Dimension (cm)': '(W x L x H) : 17.50 x 64.00 x 46.00 cm',
      'Gross Weight (kg)': '9.30 kg',
      'Volume (cm³)':   '51,520.00 cm³',
      'Keyboard Type':  'ENG/TH Keyboard',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },

  // ─── AI-COM ───────────────────────────────────────────────────
  {
    id: 'ai-001', category: 'AI-COM', brand: 'ASUS',
    model: 'NVIDIA DGX Spark Ascent GX10-GG0011BN',
    price: 189000, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':      '20-core Arm: 10 Cortex-X925 + 10 Cortex-A725',
      'Chipset':        'NVIDIA® GB10 Grace Blackwell Superchip',
      'CPU Series':     'NVIDIA Blackwell Architecture',
      'AI Performance': '• Up to 1 petaFLOP of AI performance using FP4',
      'Main Memory':    '128GB LPDDR5x unified system memory',
      'Storage':        '1TB M.2 NVMe PCIe 4.0 SSD',
      'Storage Slot':   '1x M.2 2242/2230 SSD (Occupied)',
      'Audio':          'N/A',
      'OS':             'NVIDIA DGX OS',
      'Special Feature':'NVIDIA DGX Spark – Professional AI Workstation',
      'Wireless':       'AW-EM637 Wi-Fi 7 (Gig+) 2x2',
      'Bluetooth':      'Bluetooth® 5',
      'Port':           '3x USB 3.2 Gen 2x2 Type-C (DisplayPort 2.1)\n1x USB 3.2 Gen 2x2 Type-C with PD in (180W EPR)\n1x HDMI 2.1\n1x Kensington Lock\n1x RJ-45 10GbE\n2x QSFP (ConnectX-7 Smart NIC)',
      'Network':        '10 GbE + 2x QSFP ConnectX-7',
      'Power Supply':   '• 240W Adapter\n• Power cord',
      'Dimension (cm)': '(W x L x H) : 15.00 x 15.00 x 5.10 cm',
      'Net Weight (kg)':'1.48 kg',
      'Package Dimension (cm)': '(W x L x H) : 19.00 x 15.00 x 19.00 cm',
      'Gross Weight (kg)': '3.19 kg',
      'Volume (cm³)':   '5,415.00 cm³',
      "What's in the box?": '• ASUS Ascent GX10\n• AC Adapter\n• Power Cord\n• User Manual\n• Warranty Card',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },

  // ─── PC ──────────────────────────────────────────────────────
  {
    id: 'pc-001', category: 'PC', brand: 'ASUS',
    model: 'ExpertCenter P700 SFF PM700SK-0R5330001WS',
    price: 22900, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':      'AMD Ryzen™AI 5 330 Processor (2.0GHz Up to 4.4GHz, 4C/8T, 8MB Cache)',
      'Chipset':        'AMD SoC Platform',
      'AI Engine':      'AMD Ryzen™ AI (NPU 50 TOPs)',
      'Graphics':       'Integrated: AMD Radeon Graphics',
      'Main Memory':    '16GB DDR5-5600 SO-DIMM',
      'Memory Slot':    '2x DDR5 SO-DIMM',
      'Max Memory':     'Up to 64GB',
      'Storage':        '512GB M.2 2280 NVMe PCIe 4.0 SSD',
      'Storage Slot':   '1x M.2 2280 connector (Occupied)\n1x 3.5" Drive Bay\n1x M.2 connector for WiFi',
      'Expansion Slots':'1x PCIe® 4.0 x16 (operating at x4)',
      'Audio Jack':     'High Definition 7.1 Channel Audio\n1x 3.5mm combo audio jack',
      'OS':             'Windows 11 Home + Microsoft Office Home 2024 + Microsoft 365 Basic',
      'Wireless':       'Wi-Fi 6 (802.11ax)',
      'Bluetooth':      'Bluetooth 5.2',
      'Front I/O Port': '1x USB 3.2 Gen 1 Type-C\n2x USB 3.2 Gen 1 Type-A',
      'Rear I/O Port':  '1x USB 3.2 Gen 1 Type-A\n1x Displayport 1.4\n1x HDMI 2.1b',
      'Network':        'Gigabit Ethernet',
      'CardReader':     '1x 2-in-1 card reader SD / MMC',
      'Power Supply':   '180W power supply (80+ Bronze, peak 228W)',
      'Dimension (cm)': '(W x L x H) : 9.30 x 29.60 x 30.90 cm',
      'Net Weight (kg)':'5.06 kg',
      'Keyboard':       'ENG/TH Keyboard included',
      'Mouse':          'Mouse included',
      'Volume (cm³)':   '40,800.00 cm³',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },

  // ─── Gaming Desktop ───────────────────────────────────────────
  {
    id: 'gpc-001', category: 'gaming-desktop-pc', brand: 'ASUS',
    model: 'TUF Gaming T500MV-13420H031WA',
    price: 35900, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':      'Intel Core i5-13420H (2.1GHz up to 4.6GHz, 12MB Intel Smart Cache)',
      'Chipset':        'Intel SoC Platform',
      'CPU Series':     'Core i5 13th Gen',
      'Graphics':       'NVIDIA GeForce RTX 3050 (6GB GDDR6): 1x DP, 1x HDMI, 1x DVI-D',
      'Main Memory':    '32GB (2x 16GB) DDR5 SO-DIMM',
      'Memory Slot':    '2x DDR5 SO-DIMM slot',
      'Max Memory':     '64GB',
      'Storage':        '512GB M.2 2280 NVMe PCIe 4.0 SSD',
      'Storage Slot':   '2x M.2 2280 connector\n1x 3.5" Drive Bay\n1x M.2 connector for WiFi',
      'Expansion Slots':'1x PCIe® 4.0 x16 (operating at x8)',
      'Audio Jack':     '1x 7.1 channel audio (3 ports)\n1x 3.5mm combo audio jack',
      'OS':             'Windows 11 Home + Microsoft Office Home 2024 + Microsoft 365 Basic',
      'Wireless':       'Wi-Fi 6 (802.11ax) Dual band 2x2',
      'Bluetooth':      'Bluetooth 5.2',
      'Front I/O Port': '1x USB 3.2 Gen 1 Type-C\n2x USB 3.2 Gen 1 Type-A',
      'Rear I/O Port':  '1x Displayport 1.4\n4x USB 2.0 Type-A',
      'Network':        'Gigabit Ethernet',
      'Power Supply':   '330W power supply (80+ Platinum, peak 660W)',
      'Dimension (cm)': '(W x L x H) : 15.55 x 29.64 x 34.70 cm',
      'Net Weight (kg)':'5.90 kg',
      'Package Dimension (cm)': '(W x L x H) : 24.00 x 48.50 x 50.00 cm',
      'Gross Weight (kg)': '14.00 kg',
      'Volume (cm³)':   '58,200.00 cm³',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },

  // ─── Mini PC ──────────────────────────────────────────────────
  {
    id: 'mini-001', category: 'mini-pc', brand: 'ASUS',
    model: 'NUC 14 Essential Barebone RNUC14MNK1500000',
    price: 8900, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':      'Intel N150 Processor (Up to 3.6GHz, 6MB Intel Smart Cache, TDP 6W)',
      'CPU Series':     'Intel N-Series',
      'Graphics':       'Intel Graphics (Integrated)',
      'Main Memory':    'Memory Not Included',
      'Memory Slot':    '1x DDR5 SO-DIMM slot',
      'Max Memory':     'Up to 16GB',
      'Storage':        'Storage Not Included',
      'Storage Slot':   '1x M.2 2280/2242 PCIe Gen3x4 (128GB–2TB NVMe or SATA SSD)',
      'Sound Technology':'Realtek ALC3251',
      'Audio Jack':     '1x 3.5mm Headset Jack',
      'OS':             'DOS',
      'Wireless':       'Wireless 802.11ax',
      'Bluetooth':      'Bluetooth 5.3',
      'Front I/O ports':'1x USB 3.2 Gen 2 Type-C\n2x USB 3.2 Gen 2 Type-A',
      'Back I/O ports': '1x USB 3.2 Gen 2 Type-C w/ DisplayPort 1.4\n2x USB 3.2 Gen 2 Type-A\n1x USB 2.0 Type-A\n1x HDMI 2.1\n1x DisplayPort 1.4',
      'Network':        '10/100/1000/2500 LAN',
      'Power Adapter':  '19VDC, 3.42A, 65W Power Adapter',
      'Dimension (cm)': '(W x L x H) : 13.50 x 11.50 x 3.60 cm',
      'Net Weight (kg)':'0.48 kg',
      'Package Dimension (cm)': '(W x L x H) : 17.00 x 19.00 x 10.00 cm',
      'Gross Weight (kg)': '1.32 kg',
      'Volume (cm³)':   '3,230.00 cm³',
      'Special Feature':'VESA Bracket included',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },

  // ─── Server ───────────────────────────────────────────────────
  {
    id: 'svr-001', category: 'Server', brand: 'HPE',
    model: 'ProLiant DL380 Gen10 Plus (P05172-B21#UUF)',
    price: 285000, priceUnit: 'บาท/เครื่อง',
    priceDate: '2569-05-21', priceRef: 'ราคากลาง สพร. ปี 2569',
    specs: {
      'Processor':      '2x Intel Xeon Gold 6326 (2.9GHz up to 3.5GHz, 24MB Cache)',
      'Chipset':        'Intel C621A',
      'CPU Series':     'Intel Xeon Gold',
      'Main Memory':    '32GB (2x16GB) Dual Rank x8 DDR4-3200 CAS-22-22-22 Registered Smart Memory Kit',
      'Storage':        '4 x 960GB SATA 6G Read Intensive SFF BC Multi Vendor SSD',
      'Storage Slot':   '8 x SFF (Hot Plug) Chassis',
      'Expansion Slots':'1x HPE ProLiant DL380 Gen10 Plus x8/x16/x8 Primary FIO Riser Kit',
      'Network':        'Broadcom BCM57416 Ethernet 10Gb 2-port BASE-T OCP3 Adapter for HPE',
      'Power Supply':   '2 x 800W Flex Slot Platinum Hot Plug Low Halogen Power Supply Kit',
      'Dimension (cm)': '(W x L x H) : 60.00 x 97.00 x 27.00 cm',
      'Net Weight (kg)':'29.16 kg',
      'Volume (cm³)':   '157,140.00 cm³',
      'RAID':           'MegaRAID MR416i-a x16 Lanes 4GB Cache NVMe/SAS 12G Controller',
      'System Management': 'HPE iLO',
      'Form Factor':    '2U Rack',
      'Special Feature':'1x HPE 96W Smart Storage Lithium-ion Battery with 145mm Cable Kit',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'เพิ่มข้อมูลใหม่', detail: 'นำเข้าจากไฟล์ Excel' }],
  },
];

// ─── Spec Templates (คุณลักษณะเฉพาะ) ──────────────────────────
const INITIAL_SPECS = [
  {
    id: 'sp-001',
    name: 'Notebook สำหรับงานสำนักงาน',
    category: 'Notebook',
    purpose: 'คุณลักษณะเฉพาะสำหรับจัดซื้อ Notebook ใช้งานสำนักงานทั่วไป ประจำปี 2569',
    budget: 30000,
    year: '2569', month: '05',
    createdDate: '2569-05-21',
    createdBy: 'admin',
    specs: {
      'Processor':          'Intel Core i5 หรือสูงกว่า (Gen 12 ขึ้นไป) หรือ AMD Ryzen 5 เทียบเท่า',
      'Main Memory':        'ไม่น้อยกว่า 16GB DDR5',
      'Storage':            'ไม่น้อยกว่า 512GB SSD (NVMe PCIe)',
      'Display Screen':     'ขนาดไม่น้อยกว่า 14 นิ้ว ความละเอียดไม่น้อยกว่า Full HD (1920×1080)',
      'OS':                 'Windows 11 Home หรือสูงกว่า พร้อม Microsoft Office',
      'Wireless':           'รองรับ Wi-Fi 6 (802.11ax) ขึ้นไป',
      'Bluetooth':          'Bluetooth 5.0 ขึ้นไป',
      'Battery':            'ความจุไม่น้อยกว่า 40WHrs',
      'Web Camera':         'กล้อง HD 720p ขึ้นไป',
      'Net Weight (kg)':    'น้ำหนักไม่เกิน 2.5 กิโลกรัม (รวมแบตเตอรี่)',
      'warranty':           'รับประกันไม่น้อยกว่า 1 ปี ศูนย์บริการในประเทศไทย',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'สร้างสเปคใหม่', detail: 'ตั้งค่าเริ่มต้น' }],
  },
  {
    id: 'sp-002',
    name: 'Desktop PC สำหรับงานทั่วไป',
    category: 'PC',
    purpose: 'คุณลักษณะเฉพาะสำหรับจัดซื้อ Desktop PC งานธุรการและงานเอกสาร',
    budget: 25000,
    year: '2569', month: '05',
    createdDate: '2569-05-21',
    createdBy: 'admin',
    specs: {
      'Processor':      'Intel Core i5 หรือสูงกว่า หรือ AMD Ryzen 5 เทียบเท่า',
      'Main Memory':    'ไม่น้อยกว่า 16GB DDR5',
      'Storage':        'ไม่น้อยกว่า 512GB SSD (NVMe)',
      'OS':             'Windows 11 Home หรือสูงกว่า พร้อม Microsoft Office',
      'Wireless':       'รองรับ Wi-Fi 6 (802.11ax) ขึ้นไป',
      'Network':        'รองรับ Gigabit Ethernet',
      'Power Supply':   'กำลังไฟไม่น้อยกว่า 180W มาตรฐาน 80+ Bronze',
      'warranty':       'รับประกันไม่น้อยกว่า 1 ปี ศูนย์บริการในประเทศไทย',
    },
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'สร้างสเปคใหม่', detail: 'ตั้งค่าเริ่มต้น' }],
  },
];

// ─── 3-Vendor Comparisons (เทียบราคา 3 เจ้า) ─────────────────
const INITIAL_COMPARISONS = [
  {
    id: 'cmp-001',
    name: 'เปรียบเทียบ Notebook สำนักงาน ปี 2569',
    category: 'Notebook',
    year: '2569', month: '05',
    specId: 'sp-001',
    notes: 'เปรียบเทียบราคาสำหรับจัดซื้อ Notebook จำนวน 10 เครื่อง',
    status: 'draft',
    createdDate: '2569-05-21', createdBy: 'admin',
    vendors: [
      {
        id: 'v1', name: 'บริษัท เอบีซี จำกัด',
        brand: 'ASUS', model: 'Vivobook 16 (X1607CA-MB535WA)', price: 25900,
        specs: {
          'Processor':       'Intel Core Ultra 5 225H (1.7GHz, up to 4.9GHz)',
          'Main Memory':     '16GB DDR5 Onboard',
          'Storage':         '512GB M.2 NVMe PCIe 4.0 SSD',
          'Display Screen':  '16.0" 1920×1200 WUXGA IPS 60Hz',
          'OS':              'Windows 11 Home + Microsoft Office Home 2024',
          'Wireless':        'Wireless 802.11ax (Wi-Fi 6)',
          'Battery':         '42WHrs, 3-cell Li-ion',
          'Net Weight (kg)': '1.88 kg',
          'warranty':        '1 ปี ศูนย์บริการในประเทศ',
        },
      },
      {
        id: 'v2', name: 'ห้างหุ้นส่วนจำกัด ดีอีเอฟ',
        brand: 'HP', model: 'Laptop 15s-fq5330TU', price: 24500,
        specs: {
          'Processor':       'Intel Core i5-1235U (1.3GHz, up to 4.4GHz)',
          'Main Memory':     '8GB DDR4',
          'Storage':         '512GB PCIe NVMe SSD',
          'Display Screen':  '15.6" 1920×1080 FHD IPS',
          'OS':              'Windows 11 Home',
          'Wireless':        'Wireless 802.11ax (Wi-Fi 6)',
          'Battery':         '41Wh, 3-cell',
          'Net Weight (kg)': '1.69 kg',
          'warranty':        '1 ปี ศูนย์บริการในประเทศ',
        },
      },
      {
        id: 'v3', name: 'บริษัท จีเอชไอ จำกัด',
        brand: 'Lenovo', model: 'IdeaPad 5 15IAL7', price: 26900,
        specs: {
          'Processor':       'Intel Core i5-1235U (1.3GHz, up to 4.4GHz)',
          'Main Memory':     '16GB DDR5',
          'Storage':         '512GB SSD NVMe',
          'Display Screen':  '15.6" 1920×1080 FHD IPS',
          'OS':              'Windows 11 Home + Office Home',
          'Wireless':        'Wi-Fi 6 802.11ax',
          'Battery':         '57Wh, 3-cell',
          'Net Weight (kg)': '1.70 kg',
          'warranty':        '2 ปี ศูนย์บริการในประเทศ',
        },
      },
    ],
    editHistory: [{ date: '2569-05-21', user: 'admin', action: 'สร้างการเปรียบเทียบใหม่', detail: 'ตัวอย่างข้อมูล' }],
  },
];

// Export globals
Object.assign(window, { CATEGORIES, CAT_COLORS, SPEC_GROUPS, USERS, INITIAL_PRODUCTS, INITIAL_SPECS, INITIAL_COMPARISONS });
